apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  namespace: openshift-logging
  name: instance
spec:
  collection:
    logs:
      fluentd: {}
      type: fluentd
  curation:
    curator:
      schedule: 30 3 * * *
    type: curator
  logStore:
    elasticsearch:
      nodeCount: 3
      resources:
        requests:
          memory: "4Gi"
        limits:
          memory: "4Gi"
      redundancyPolicy: SingleRedundancy
      storage:
        size: 100G
        storageClassName: ocs-storagecluster-ceph-rbd
    retentionPolicy:
      application:
        maxAge: 3d
      infra:
        maxAge: 3d
      audit:
        maxAge: 7d
    type: elasticsearch
  managementState: Managed
  visualization:
    kibana:
      replicas: 1
    type: kibana

